fieldLayouts:
  d2ead231-a1bc-4718-83bb-6d9eb17e143f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: eb8a4857-a377-49e6-bdc9-e4e261e9a1d0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6c6103e8-2324-47cb-8ac9-24e9a44bd198
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 892c1859-9d80-45f3-a599-6bc22213995b # Trees Section
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
