fieldLayouts:
  6a3f1146-31c1-4b27-9a5a-e9ea389b229f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 950aad81-3a61-4e45-96f2-eb24ccc18594
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 65e78207-4cc0-4cc2-8137-f37582a23d05
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 9db6f2dc-5ee6-4f87-a572-3fe14af8ba1f # About Articles
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
