fieldLayouts:
  b0e4e2e1-39d0-49f2-bf3f-43b5177b72f6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1162f604-5a99-412c-a441-226439ec6091
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e7a6fa66-488e-4eec-b245-fafd1fb05c5c # Header Logo
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30c0d5f1-5003-49f4-abea-e3d978b1fcca
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c0014503-8109-454b-8ca4-65d8a6bc2969
        userCondition: null
handle: header
hasTitleField: false
name: Header
section: cc39aeb2-6862-411f-a182-99eb82df8806 # Header
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
