fieldLayouts:
  3ac446bd-bf3b-484b-9166-dfc6a1c1b210:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 92b3dfaa-acdb-4b50-9bfa-6c9d280e257d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f817d004-c851-42a2-a118-3b5bb3cf7b80 # Section Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02c737cd-2b81-4122-9998-7b5d00724a90
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 910607eb-e39b-49f1-acbf-996482736ff2
        userCondition: null
handle: homeAboutSection
hasTitleField: false
name: 'Home About Section'
section: a934eed7-50b0-4069-bd63-9ee5af8a4d20 # Home About Section
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
