fieldLayouts:
  a18f1277-75fb-42e5-9d9a-f33ae0169293:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 970aae6c-0af6-4a84-ac33-39a0987c51aa
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: true
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: ff726012-78d1-4b6e-8613-149af364c1a8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4959549f-fd36-490c-b4f9-31d18d06d09d
        userCondition: null
fs: assets
handle: treesAssets
name: 'Trees Assets'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
