columnSuffix: ssuzqomh
contentColumnType: integer(10)
fieldGroup: 24d81c84-bda5-49fb-b1e5-0c1681f48834 # Trees Section
handle: matureSizeHeight
instructions: null
name: 'Mature Size (Height)'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: 'ft. tall'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
