columnSuffix: gyvthpud
contentColumnType: string(12)
fieldGroup: 24d81c84-bda5-49fb-b1e5-0c1681f48834 # Home Trees Section
handle: nativeAreas
instructions: null
name: 'Native Areas'
searchable: false
settings:
  columnType: null
  options:
    -
      __assoc__:
        -
          - label
          - 'North America'
        -
          - value
          - northAmerica
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
