columnSuffix: rhhinmav
contentColumnType: text
fieldGroup: e85c4278-feb8-4a9d-b3d8-ee47e782725e # Home Hero Section
handle: sectionParagraph
instructions: null
name: 'Section Paragraph'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
