columnSuffix: null
contentColumnType: string
fieldGroup: 24d81c84-bda5-49fb-b1e5-0c1681f48834 # Trees Section
handle: storeAreas
instructions: null
name: 'Store Areas'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  sources:
    - 'section:1ecc13eb-5d8e-4e2c-b6b9-05bb67c8963c' # Store Areas
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
