columnSuffix: yrllsqxn
contentColumnType: text
fieldGroup: e85c4278-feb8-4a9d-b3d8-ee47e782725e # Home Hero Section
handle: videoHeader
instructions: null
name: 'Video Header'
searchable: false
settings:
  url: ''
translationKeyFormat: null
translationMethod: none
type: wrav\oembed\fields\OembedField
