dateModified: 1703372686
email:
  fromEmail: r0900654@student.thomasmore.be
  fromName: 'Support Trees'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  assets:
    hasUrls: true
    name: Assets
    settings:
      path: '@webroot/assets'
    type: craft\fs\Local
    url: '@web/assets'
meta:
  __names__:
    6a0b1761-f669-4f5b-85e6-9978bee753d6: 'Trees Assets' # Trees Assets
    53973bd1-6806-4012-81fa-59993f391e9d: header # header
    773026d7-893c-46bb-9217-5e3c6b935c98: 'Support Trees' # Support Trees
    c225c914-5b17-456c-962e-5d652d556c82: 'Rich Text' # Rich Text
    cc39aeb2-6862-411f-a182-99eb82df8806: header # header
    ee746d06-a2cd-49ba-8254-f3c9b022431c: 'Support Trees' # Support Trees
    efd20e6b-636c-4c56-bfcb-514a4816314b: Common # Common
plugins:
  abm-tinymce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Support Trees'
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
