defaultPlacement: end
enableVersioning: true
handle: aboutArticles
name: 'About Articles'
propagationMethod: all
siteSettings:
  ee746d06-a2cd-49ba-8254-f3c9b022431c: # Support Trees
    enabledByDefault: true
    hasUrls: true
    template: about-articles/_entry
    uriFormat: 'about-articles/{slug}'
type: channel
