defaultPlacement: end
enableVersioning: true
handle: detailHeader
name: 'Detail Header'
propagationMethod: all
siteSettings:
  ee746d06-a2cd-49ba-8254-f3c9b022431c: # Support Trees
    enabledByDefault: true
    hasUrls: true
    template: detail-header/_entry
    uriFormat: 'detail-header/{slug}'
type: channel
