defaultPlacement: end
enableVersioning: true
handle: heroVideoSection
name: 'Hero Video Section'
propagationMethod: all
siteSettings:
  ee746d06-a2cd-49ba-8254-f3c9b022431c: # Support Trees
    enabledByDefault: true
    hasUrls: true
    template: hero-video/_entry
    uriFormat: hero-video
type: single
